# Generated by Django 2.0.2 on 2018-02-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=250)),
                ('property_address1', models.CharField(max_length=250)),
                ('property_address2', models.CharField(max_length=250)),
                ('property_address3', models.CharField(max_length=250)),
                ('property_address4', models.CharField(max_length=250)),
                ('unit_name', models.CharField(max_length=250)),
                ('tenant_name', models.CharField(max_length=250)),
                ('lease_start_date', models.DateTimeField(verbose_name='lease start date')),
                ('lease_end_date', models.DateTimeField(verbose_name='lease end date')),
                ('lease_years', models.IntegerField(default=0)),
            ],
        ),
    ]
