# Generated by Django 2.0.2 on 2018-02-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='current_rent',
            field=models.FloatField(default=0),
        ),
    ]
