# Generated by Django 2.0.2 on 2018-02-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0002_data_current_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='property_address1',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='data',
            name='property_address2',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='data',
            name='property_address3',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='data',
            name='property_address4',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
