# Generated by Django 2.0.2 on 2018-02-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0004_auto_20180224_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='lease_end_date',
            field=models.DateField(blank=True, verbose_name='lease end date'),
        ),
        migrations.AlterField(
            model_name='data',
            name='lease_start_date',
            field=models.DateField(blank=True, verbose_name='lease start date'),
        ),
    ]
