# Generated by Django 2.0.2 on 2018-02-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0007_auto_20180224_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='property_address1',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='data',
            name='property_address2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='data',
            name='property_address3',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='data',
            name='property_address4',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
