# Generated by Django 2.0.2 on 2018-02-24 20:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0010_auto_20180224_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='lease_end_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='lease_start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
