# Generated by Django 2.0.2 on 2018-02-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0013_auto_20180224_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='current_rent',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='lease_years',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='property_address1',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='property_address2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='property_address3',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='property_address4',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='property_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='tenant_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='unit_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
