# Generated by Django 2.0.2 on 2018-02-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0014_auto_20180224_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='property_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='tenant_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='unit_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
