# Generated by Django 2.0.2 on 2018-02-24 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0015_auto_20180224_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='current_rent',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='lease_end_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='data',
            name='lease_start_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='data',
            name='lease_years',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='property_address1',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='data',
            name='property_address2',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='data',
            name='property_address3',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='data',
            name='property_address4',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='data',
            name='property_name',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='data',
            name='tenant_name',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='data',
            name='unit_name',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
