# Generated by Django 2.0.2 on 2018-02-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0016_auto_20180224_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='property_address1',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='data',
            name='property_name',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='data',
            name='tenant_name',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='data',
            name='unit_name',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
