# Generated by Django 2.0.2 on 2018-02-25 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0017_auto_20180225_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='property_address1',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
